### PR TITLE
updated all Notes

### PR DESCRIPTION
**Pull request by sandeepatel01**
updated all Notes and readme file

### CODE REVIEW

**Comment by sandeepatel01** [comment]
updated all Notes and readme file.

**Comment by khushiteli** [comment]
> updated all Notes and readme file

For more notes you have to wait some time because of collage I have backlog in course I will update readme file asap. Thank you .

**Comment by sandeepatel01** [comment]
merge my updated notes and readme file in main branch

**Comment by khushitelii** [comment]
Sorry, I can not merge it to main branch whatever the notes I posted is verified by others also so I can not merge notes without verify them ....

**Comment by sandeepatel01** [comment]
thank you  Khushi 👌

**Pull request merged**
